[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
sol-ez = { workspace = true }

# external
borsh = "1.5"
solana-program = "2.2"

[build-dependencies]
sol-gen = { workspace = true }
