[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
sol-ez = { workspace = true }

# external
borsh = { workspace = true, features = ["derive"] }
pinocchio = { workspace = true }
pinocchio-log = "0.4"

[build-dependencies]
sol-gen = { workspace = true }
