[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
sol-ez = { workspace = true }

# external
borsh = { version = "1.5", features = ["derive"] }
pinocchio = "0.8"
pinocchio-log = "0.4"

[build-dependencies]
sol-gen = { workspace = true }
