[package]
name = "sol-ez"
version = "0.1.0"
edition = "2021"

[dependencies]
# local
sol-derive = { workspace = true }

# external
borsh = { workspace = true }
pinocchio = { workspace = true }
pinocchio-system = { workspace = true }

[features]
default = []
std = []
