[program]
name = "counter"
version = [0, 1, 0]

################################################################################
# Count Account 
################################################################################

[accounts.count]
bump = true
seed = "[user] => hello + user"

[accounts.count.payload]
type = "struct"
data = { value = "u8" }

################################################################################

################################################################################
# Instruction Config
################################################################################

[ix_config]
discriminator_size = 4
discriminator_type = "hash"

################################################################################
# Initalize Instruction
################################################################################

[ix.initalize.args]
amount = "u8"

[ix.initalize.accounts]
user = { idx = 0, mutable = true, signed = true }
count = { idx = 1, type = "count", create = true, seed = ["user"] }

################################################################################
# Increment Instruction
################################################################################

[ix.increment.accounts]
user = { idx = 0, mutable = true, signed = true }
count = { idx = 1, type = "count", mutable = true, seed = ["user"] }

################################################################################
# Close Instruction
################################################################################

[ix.close.accounts]
user = { idx = 0, mutable = true, signed = true }
count = { idx = 1, type = "count", mutable = true, seed = ["user"] }

################################################################################

################################################################################
# Increment Event 
################################################################################

[event.increment]
value = "u8"
