[program]
name = "counter"
version = [0, 1, 0]

################################################################################
# Count Account 
################################################################################

[accounts.count]
id = 0
discriminator = { kind = "hash", size = 4 }
seed = { func = "[user] => 'count' + user", bump = true }

[accounts.count.payload]
type = "struct"
data = { value = "u8" }

################################################################################

################################################################################
# Instruction Config
################################################################################

[ix_config]
discriminator_size = 4
discriminator_type = "hash"

################################################################################
# Initalize Instruction
################################################################################
[ix.initalize]
id = 0

[ix.initalize.args]
amount = "u8"

[ix.initalize.accounts]
user = { id = 0, mutable = true, signed = true }
count = { id = 1, type = "count", create = true, seed = ["user"] }

################################################################################
# Increment Instruction
################################################################################
[ix.increment]
id = 1

[ix.increment.accounts]
user = { id = 0, mutable = true, signed = true }
count = { id = 1, type = "count", mutable = true, seed = ["user"] }

################################################################################
# Close Instruction
################################################################################
[ix.close]
id = 2

[ix.close.accounts]
user = { id = 0, mutable = true, signed = true }
count = { id = 1, type = "count", mutable = true, seed = ["user"] }

################################################################################

################################################################################
# Increment Event 
################################################################################

[event.increment]
value = "u8"
